### ISSUE TITLE
transactions eat line numbers

### ISSUE THREAD

**Issue by shoover** [richhickey/clojure-clr#44]
If an exception is thrown from inside a dosync transaction, the stacktrace stops at the transaction call. I confirmed this with an exception thrown from the dosync form and from a function called from the dosync form. In the stracktrace below, irc.clj line 74 contains just "(dosync".

```
  ;; expecting more frames here
  at clojure.lang.LockingTransaction.Run(IFn fn) in C:\Users\Shawn\dev\clojure-clr\Clojure\Clojure\Lib\LockingTransaction.cs:line 645
  at clojure.lang.LockingTransaction.runInTransaction(IFn fn) in C:\Users\Shawn\dev\clojure-clr\Clojure\Clojure\Lib\LockingTransaction.cs:line 524
  at irc$fn__109$user_nick__111.__invokeHelper_2(irc$fn__109$user_nick__111_base this, Object user, Object args) in irc.clj:line 74
  at irc$fn__109$user_nick__111.invoke(Object , Object )
  at clojure.lang.Var.invoke(Object arg1, Object arg2) in C:\Users\Shawn\dev\clojure-clr\Clojure\Clojure\Lib\Var.cs:line 628
  at irc$fn__231$handle__233.__invokeHelper_3(irc$fn__231$handle__233_base this, Object user, Object transitions, Object line) in irc.clj:line 171
  at irc$fn__231$handle__233.invoke(Object , Object , Object )
  at irc$fn__239$user_loop__241.__invokeHelper_2(irc$fn__239$user_loop__241_base this, Object user, Object socket) in irc.clj:line 180
  at irc$fn__239$user_loop__241.invoke(Object , Object )
  at irc$fn__248$spawn__250$fn__251.__invokeHelper_0(irc$fn__248$spawn__250$fn__251_base this) in irc.clj:line 194
```

**Comment by shoover** [comment]
Fixed in 01ca7161ede68639adc3585c17c39ab385c257ea
